baseurl = "/espm-157"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "ESPM 157"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Carl Boettiger"
  bio = ""
  job = "Assistant Professor"
  location = "UC Berkeley"
  gravatarEmail = "cboettig@gmail.com"
  # Your profile picture
#  picture = ""
  twitter = "cboettig"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class='sidebar-button-icon fa fa-lg fa-home'></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "modules"
  name = "Modules"
  pre = "<i class='material-icons'>dashboard</i>"
  url = "/modules"
[[menu.main]]
  weight = 3
  identifier = "tutorials"
  name = "Tutorials"
  pre = "<i class='material-icons'>build</i>"
  url = "/tutorials"
[[menu.main]]
  weight = 4
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class='material-icons'>date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class='material-icons'>gavel</i>"
  url = "/policies"


[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Team Repos"
  pre = "<i class='button-icon fa fa-2x fa-github'></i>"
  url = "https://github.com/espm-157"
[[menu.footer]]
  weight = 3
  identifier = "Piazza"
  name = "Forum"
  pre = "<i class='material-icons'>forum</i>"
  url = "http://piazza.com/berkeley/fall2019/espm157"
[[menu.footer]]
  weight = 4
  name = "Textbook"
  pre = "<i class='material-icons'>book</i>"
  url = "http://r4ds.had.co.nz/"
[[menu.footer]]
  weight = 5
  name = "Travis-CI"
  pre = "<i class='material-icons'>check_circle</i>"
  url = "http://travis-ci.com/espm-157/"
[[menu.footer]]
  weight = 6
  name = "DataCamp"
  pre = "<i class='material-icons'>video_library</i>"
  url = "https://www.datacamp.com/enterprise/espm-157-data-science-for-global-change-ecology-aa13375c-ddc0-41aa-9afd-4ab883028f72"



[[menu.sidebar]]
  weight = 1
  pre = "<i class='material-icons'>timeline</i>"
  name = "Climate Change"
  url = "#climate"
[[menu.sidebar]]
  weight = 2
  pre = "<i class='material-icons'>directions_boat</i>"
  name = "Overfishing"
  url = "#fish"
[[menu.sidebar]]
  weight = 3
  pre = " <i class='material-icons'>bug_report</i>"
  name = "Ecological Simulation"
  url = "#popdyn"
[[menu.sidebar]]
  weight = 4
  pre = " <i class='material-icons'>my_location</i>"
  name = "Geospatial"
  url = "#spatial"
 [[menu.sidebar]]
weight = 5
  pre = " <i class='material-icons'>trending_down</i>"
  name = "Mass Extinctions"
  url = "#extinction"



[[menu.tools]]
  weight = 1
  name = "GitHub"
  url = "#github"
  pre = "<i class='fa fa-github'></i>"
[[menu.tools]]
  weight = 3
  name = "Travis-CI"
  url = "#travis"
  pre = "<i class='material-icons'>check_circle</i>"
[[menu.tools]]
  weight = 2
  name = "RMarkdown"
  url = "#rmarkdown"
  pre = "<br/><img src='/img/rmarkdown.png' alt='rmarkdown' width='36' height='36'><br/>"
[[menu.tools]]
  weight = 4
  name = "R Packages"
  url = "#packages"
  pre = "<i class='fa fa-archive'></i>"
[[menu.tools]]
  weight = 5
  name = "Docker"
  url = "#docker"
  pre = "<i class='fa fa-docker'></i>"
[[menu.tools]]
  weight = 6
  name = "Cloud"
  url = "#cloud"
  pre = "<i class='fa fa-cloud'></i>"  
[[menu.tools]]
  weight = 7
  name = "Web design"
  url = "#website"
  pre = "<i class='material-icons'>language</i>"
[[menu.tools]]
  weight = 8
  name = "Shiny"
  url = "#shiny"
  pre = "<br/><img src='/img/shiny.png' alt='shiny' width='36' height='36'><br/>"

[params]
  dateFormat = "January 2, 2006"
  background = "https://climate.nasa.gov/system/internal_resources/details/original/417_1263_banner-science-1600x500.jpg"
  math = "true"
